version: "3"
services:
  nextcloud:
    container_name: nextcloud
    restart: always
    image: linuxserver/nextcloud
    volumes:
      - ${USERDIR}/docker/nextcloud/config:/config
      - ${USERDIR}/docker/nextcloud/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAINNAME}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=mydnschallenge"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https"
  mysql:
    container_name: nextcloud_mysql
    restart: always
    image: mariadb:latest
    volumes:
      - ${USERDIR}/docker/nextcloud/mysql:/var/lib/mysql
    networks:
      - traefik_proxy
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    labels:
      - "traefik.enable=false"
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
